### ISSUE TITLE
InvMove

### ISSUE THREAD

**Issue by Paulino0o** [Leawind/Third-Person#154] opened 2024-09-09 10:46 UTC
## Describe

This mod allows the player to move with the inventory and other GUI open. When the player's back is facing the camera it works fine, but if you open the inventory with the player facing the camera, the movement inputs will be mirrored (to be more precise, the wasd keys move the character relative to where its facing, instead of where the camera is facing)

## Reproduce

1- Move the character towars the camera (press S for exemple)
2- Open inventory
3-try to move with wasd

## Expected behavior

It should keep moving relative to the camera and not the character direction.

**Comment by twigtarsier** [comment] 2024-09-18 21:02
duplicate of #103

**Closed as not planned** 2024-10-09 07:53 UTC
Labels: duplicate, compat
