### ISSUE TITLE
Start sprinting randomly

### ISSUE THREAD

**Issue by ghost** [Leawind/Third-Person#159] opened 2024-10-08 16:58 UTC
## Describe the bug

My character start sprinting when double tapping A or S or D, even when i tap D then S fast, my character start sprinting and this is annoying.

## Reproduce

Go in 3rd person with the mod, go forward then double tap A or S or D and it will start printing.

## Expected behavior

I expect that my character start sprinting only when i double tap W.

## Additional context

No additional context

**Comment by Leawind** [comment] 2024-10-09 07:31
Duplicate of #155

**Closed as not planned by Leawind** 2024-10-09 07:31 UTC
Labels: bug, duplicate
